name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  # pull_request:
    # branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: |
        git config --global user.name "hcyoon0511@naver.com"
        git config --global user.email "yoonheecheol"
    - run: yarn install --immutable --immutable-cache --check-cache
    - run: yarn build

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
